name: Build Geode Mod

on:
  workflow_dispatch:
  push:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
          - name: Android 64-bit
            target: Android64
          - name: Android 32-bit
            target: Android32

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Mod
        uses: geode-sdk/build-geode-mod@v3
        with:
          target: ${{ matrix.config.target }}
